# Generated by Django 2.1.3 on 2018-12-05 22:28

from django.db import migrations, models
import pessoas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('idade', models.IntegerField()),
                ('foto1', models.ImageField(upload_to=pessoas.models.salvar_imagem)),
                ('foto2', models.ImageField(upload_to=pessoas.models.salvar_imagem)),
                ('foto3', models.ImageField(upload_to=pessoas.models.salvar_imagem)),
                ('foto4', models.ImageField(upload_to=pessoas.models.salvar_imagem)),
                ('foto5', models.ImageField(upload_to=pessoas.models.salvar_imagem)),
                ('foto6', models.ImageField(upload_to=pessoas.models.salvar_imagem)),
            ],
        ),
    ]
